<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>AEC AB</Authors>
    <!-- 
    Adjust MainRevitVersion to get IntelliSense for the correct version do a 
    dotnet restore to restore the correct nuget packages for the selected Revit version.
    -->
    <MainRevitVersion Condition="'$(Configuration)' == 'Debug'">2026</MainRevitVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project=".\Configurations.targets" />

</Project>