<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>AEC AB</Authors>
    <Version>0.0.1</Version>
    <Title>AutoCADAutomationExtension</Title>
    <Description>AutoCADAutomationExtension Description</Description>
    <!-- 
		Adjust MainAutoCADVersion to get IntelliSense for the correct version do a 
		dotnet restore to restore the correct nuget packages for the selected AutoCAD version.
		-->
		<MainAutoCADVersion Condition="'$(Configuration)' == 'Debug'">2026</MainAutoCADVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project=".\Configurations.targets" />

</Project>