<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>AEC AB</Authors>
    <Version>0.0.1</Version>
    <Title>TeklaAutomationExtension</Title>
    <Description>TeklaAutomationExtension Description</Description>
    <!-- 
		Adjust MainTeklaVersion to get IntelliSense for the correct version do a 
		dotnet restore to restore the correct nuget packages for the selected Tekla version.
		-->
    <MainTeklaVersion Condition="'$(Configuration)' == 'Debug'">2026</MainTeklaVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project=".\Configurations.targets" />

</Project>