<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>AEC AB</Authors>
    <Version>0.0.1</Version>
    <Title>RevitAppExtension</Title>
    <Description>RevitAppExtension Description</Description>
    <!-- 
		Adjust MainRevitVersion to get IntelliSense for the correct version do a 
		dotnet restore to restore the correct nuget packages for the selected Revit version.
		-->
		<MainRevitVersion Condition="'$(Configuration)' == 'Debug'">2026</MainRevitVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <Import Project="Configurations.targets" />

  <Choose>
    <When Condition="$(Configuration.Contains('Design'))">
      <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <XamlDebuggingInformation>True</XamlDebuggingInformation>
      </PropertyGroup>
    </When>
    <Otherwise>
      <!-- For library mode, exclude App.xaml entirely -->
      <PropertyGroup>
        <OutputType>Library</OutputType>
      </PropertyGroup>
      <ItemGroup>
        <ApplicationDefinition Remove="App.xaml" />
        <Page Remove="App.xaml" />
        <Compile Remove="App.xaml.cs" />
        <None Include="App.xaml" />
        <None Include="App.xaml.cs" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <ItemGroup>
		<PackageReference Include="WPF-UI" Version="4.0.2" />
  </ItemGroup>

</Project>