<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ExtensionId>NavisworksAutomationExtension</ExtensionId>
    <Authors>AEC AB</Authors>
    <Version>0.0.1</Version>
    <Title>NavisworksAutomationExtension</Title>
    <Description>NavisworksAutomationExtension Description</Description>
    <PackageTags>Navisworks;Assistant;Extension</PackageTags>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageIconUrl></PackageIconUrl>
    <!-- 
    Adjust MainNavisworksVersion to get IntelliSense for the correct version do a 
    dotnet restore to restore the correct nuget packages for the selected Navisworks version.
    -->
    <MainNavisworksVersion Condition="'$(Configuration)' == 'Debug'">2024</MainNavisworksVersion>
    <NavisworksPlatformBuildDir>$(MSBuildThisFileDirectory)../../platforms/NavisworksPlatform/build/</NavisworksPlatformBuildDir>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <Import Project="$(NavisworksPlatformBuildDir)CW.Assistant.Extensions.Templates.Platform.Navisworks.props" Condition="Exists('$(NavisworksPlatformBuildDir)CW.Assistant.Extensions.Templates.Platform.Navisworks.props')" />

  <ItemGroup Condition="!Exists('$(NavisworksPlatformBuildDir)CW.Assistant.Extensions.Templates.Platform.Navisworks.props')">
    <PackageReference Include="CW.Assistant.Extensions.Templates.Platform.Navisworks" Version="26.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="$(NavisworksPlatformBuildDir)CW.Assistant.Extensions.Templates.Platform.Navisworks.targets" Condition="Exists('$(NavisworksPlatformBuildDir)CW.Assistant.Extensions.Templates.Platform.Navisworks.targets')" />
</Project>
